version: "3"

tasks:
  default:
    cmds:
      - task: dependency
      - task: fmt
      - task: check
      - task: test
  dependency:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/daixiang0/gci@latest
      - go install github.com/client9/misspell/cmd/misspell@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  fmt:
    cmds:
      - gofmt -s -w -l .
      - echo 'goimports' && goimports -w -local github.com/omegaatt36/instagramrobot $(find . -type f -name '*.go')
      - gci write -s standard -s default -s "Prefix(github.com/omegaatt36/instagramrobot)" --skip-generated .
      - go mod tidy
  check:
    cmds:
      - go vet -all ./...
      - golangci-lint run
      - misspell -error */**
      - echo 'staticcheck' && staticcheck $(go list ./...)
  test:
    cmds:
      - go test ./...
  live-web:
    cmds:
      - air --build.cmd "go build -o build/web cmd/web/main.go" --build.bin "./build/web"
  live-bot:
    cmds:
      - air --build.cmd "go build -o build/bot cmd/bot/main.go" --build.bin "./build/bot"
  live-all:
    cmds:
      - task: live-web &
      - task: live-bot
